### ISSUE TITLE
Add toml config support

### ISSUE THREAD

**Issue by tharvik** [BenjaminSchubert/Pyckup#18]
[TOML](https://github.com/toml-lang/toml) is a powerful configuration language, aimed at being the human writable counterpart to JSON.

For example, we can have
```toml
# defaults for all profiles
date_format = "%Y.%m.%d-%H-%M-%S"

[local]
source = "/"
destination = "/mnt/backup"
# exclude containing "/" for specific file exclusion 
exclude = [ "/tmp", "/media" ]

[local.home]
# relative to local.source
# will sync to local.destination + local.home.source if no local.home.destination key
source = "home"
# exclude without "/" for recursive exclude pattern based on fnmatch(3)
exclude = [ ".serverauth*" ]

[local.var]
source = "var"
exclude = [ "./cache", "./db" ]
```
which gives the following JSON
```json
{
    "date_format": "%Y.%m.%d-%H-%M-%S",
    "local": {
        "source": "/",
        "destination": "/mnt/backup",
        "exclude": [
            "/tmp",
            "/media"
        ],
        "home": {
            "source": "home",
            "exclude": [
                ".serverauth*"
            ]
        },
        "var": {
            "source": "var",
            "exclude": [
                "./cache",
                "./db"
            ]
        }
    }
}
```

We can add more typing logic, but that would clobber the user easyness to write a config file IMO.
